<?xml version="1.0"?>
<robot name="macro" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="cylinder_inertial" params="mass radius length oz roll pitch yaw">
        <inertial>
        <origin xyz="0 0 ${oz}" rpy="${roll} ${pitch} ${yaw}"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass*(3*radius*radius+length*length)/12}"
            iyy="${mass*(3*radius*radius+length*length)/12}"
            izz="${mass*radius*radius/2}"
            ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertial" params="mass radius">
        <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${mass*(2*radius*radius)/5}"
            iyy="${mass*(2*radius*radius)/5}"
            izz="${mass*(2*radius*radius)/5}"
            ixy="0" iyz="0" ixz="0"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel">
            <visual>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial mass="0.05" radius="${wheel_radius}" length="${wheel_length}" oz="0" roll="${pi/2}" pitch="0" yaw="0"/>
        </link>
        <joint name="base_to_${prefix}_wheel" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${-base_radius/2} ${reflect*(2*base_radius/3)} 0"/>
        </joint>
    </xacro:macro>
</robot>