<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="base_color_arg" default="Green"/>

    <xacro:include filename="$(find in424_desc)/xacro/materials.xacro"/>
    <xacro:include filename="$(find in424_desc)/xacro/robot.gazebo"/>
    <xacro:include filename="$(find in424_desc)/xacro/macro.xacro"/>

    <xacro:property name="base_radius" value="0.25"/>
    <xacro:property name="base_length" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_length" value="0.03"/>
    <xacro:property name="front_wheel_radius" value="${wheel_radius/2+0.01}"/>
    <xacro:property name="lidar_radius" value="0.03"/>
    <xacro:property name="lidar_length" value="0.015"/>


    <!-- *****************BASE LINK************************* -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_length/2}"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
            <material name="$(arg base_color_arg)"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_length/2}"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="0.5" radius="${base_radius}" length="${base_length}" oz="${base_length/2}" roll="0" pitch="0" yaw="0"/>
    </link>
    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <!-- *****************REAR WHEELS************************* -->
    <xacro:wheel prefix="left" reflect="1" />
    <xacro:wheel prefix="right" reflect="-1" />


    <!-- *****************FRONT WHEEL************************* -->
    <link name="front_wheel">
        <visual>
        <geometry>
            <sphere radius="${front_wheel_radius}"/>
        </geometry>
        <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${front_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:sphere_inertial mass="0.1" radius="${front_wheel_radius}"/>
    </link>
    <joint name="base_link_to_front_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="front_wheel"/>
        <origin xyz="${base_radius-2*front_wheel_radius} 0 ${-front_wheel_radius/2}"/>
    </joint>


    <!-- *****************LIDAR************************* -->
    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>
    <joint name="base_to_lidar" type="fixed">
      <parent link="base_link"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 ${base_length + lidar_length/2}"/>
    </joint>
</robot>