#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'in424-nav','console_scripts','tf_publishers'
__requires__ = 'in424-nav'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('in424-nav', 'console_scripts', 'tf_publishers')()
    )
